version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- MongoDB__ConnectionString=mongodb://@mongodb:27017
      #- MongoDB__DatabaseName=MyLittleLibrary
    depends_on:
      - mongodb
    networks:
      - manga-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - manga-network
    environment:
      - MONGO_INITDB_DATABASE=MyLittleLibrary
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=
      #- MONGO_SERVICE_USERNAME=
      #- MONGO_SERVICE_PASSWORD=


networks:
  manga-network:
    driver: bridge

volumes:
  mongodb_data: